# Generated by Django 2.0.2 on 2018-06-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Litigation', models.BooleanField()),
                ('Corporate', models.BooleanField()),
                ('Real_Estate', models.BooleanField()),
                ('Tax', models.BooleanField()),
                ('Trusts_and_Estates', models.BooleanField()),
                ('Employment', models.BooleanField()),
                ('Environmental', models.BooleanField()),
                ('Compliance', models.BooleanField()),
                ('Regulatory', models.BooleanField()),
                ('International', models.BooleanField()),
                ('Other', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=1000)),
                ('client_name', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('position_state', models.CharField(blank=True, max_length=2, null=True)),
                ('position_city', models.CharField(blank=True, max_length=200, null=True)),
                ('position_location', models.CharField(max_length=1000)),
                ('position_description', models.TextField(max_length=100000)),
                ('position_link', models.URLField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=1000000, null=True)),
                ('accept_terms', models.BooleanField()),
                ('legal_field', models.ManyToManyField(blank=True, to='content.LegalField')),
                ('legal_fields', models.ManyToManyField(blank=True, to='content.LegalFields')),
                ('states', models.ManyToManyField(blank=True, default='Alabama', to='content.State')),
            ],
        ),
        migrations.CreateModel(
            name='PrePosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=1000)),
                ('client_name', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, help_text='Enter as YYYY-MM-DD.', null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('position_state', models.CharField(blank=True, help_text='Enter State Abbreviation.', max_length=2, null=True)),
                ('position_city', models.CharField(blank=True, max_length=200, null=True)),
                ('position_location', models.CharField(blank=True, help_text='Enter as City, State Abbreviation.', max_length=1000, null=True)),
                ('position_description', models.TextField(help_text='Expand the text box size by dragging the lower right corner.', max_length=100000)),
                ('position_link', models.URLField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, help_text='Leave blank.', max_length=1000000, null=True)),
                ('accept_terms', models.BooleanField()),
                ('legal_field', models.ManyToManyField(blank=True, to='content.LegalField')),
                ('legal_fields', models.ManyToManyField(blank=True, to='content.LegalFields')),
                ('states', models.ManyToManyField(blank=True, to='content.State')),
            ],
        ),
    ]
